version: '2'
services:
  node:
    container_name: kiran-rambha
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    networks:
      - kiranrambha-network

networks:
  kiranrambha-network:
    driver: bridge